name: Run tests
on:
  push:

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run tests
        run: |
          npm i
          npm run test

      - name: Report coverage
        uses: coverallsapp/github-action@v2

  linux-integration-tests:
    name: Run integration tests on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: |
          npm i --production
          npm run test:integration

  win-integration-tests:
    name: Run integration tests on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        node:
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: |
          npm i --production
          npm run test:integration
